# Generated by Django 4.1.2 on 2022-11-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('cnpj', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('descricao', models.TextField()),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
