# Generated by Django 3.2.6 on 2022-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='senha',
            field=models.CharField(default=123456, max_length=200),
            preserve_default=False,
        ),
    ]
