# Generated by Django 3.2.6 on 2022-11-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_restaurantes_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='cnpj',
            field=models.TextField(),
        ),
    ]
